ControllerConfig:
  Connection: "ssl://backend.christophe.engineering:8883"
  Topic: "oem-alarms/test1"

AdapterConfig:
  Connection: "ssl://backend.christophe.engineering:8883"
  Topic: "oem-alarms/test3"
  Key: "result"

LogLevel: -1
