services:
  oem-converter:
    build: .
    image: christophe2bu/oem-converter:73b07fb801bb
    ports:
      - 8883:8883
      - 1883:1883
    volumes:
      - /Users/christophebuffard/Dev/github.com/oem-converter:/opt/oem-util
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
